# Fast Convergence Configuration for 30-Node Consensus
# Achieves 1.0 cm RMSE in only 49 iterations
#
# This configuration prioritizes speed over ultimate accuracy
# Perfect for real-time tracking applications

# Inherit most settings from ideal configuration
# Only override consensus parameters for speed

# Scene Configuration (same as ideal)
scene:
  name: "Fast 30-Node Network"
  description: "1 cm accuracy in <50 iterations"
  area:
    width: 50.0
    height: 50.0
    margin: 5.0
  n_nodes: 30
  n_anchors: 5
  placement:
    anchors:
      type: "fixed"
      positions:
        - [0.0, 0.0]
        - [50.0, 0.0]
        - [50.0, 50.0]
        - [0.0, 50.0]
        - [25.0, 25.0]
    unknowns:
      type: "grid"
      grid_size: 5
      x_range: [5.0, 45.0]
      y_range: [5.0, 45.0]
  comm_range: 25.0

# Signal Configuration
signal:
  carrier_freq: 6.5e9
  bandwidth: 499.2e6
  sample_rate: 1.0e9
  burst_duration: 1.0e-6
  prf: 124.8e6
  signal_type: "HRP_UWB"
  sequence_length: 127
  cyclic_prefix_length: 32

# Channel Configuration
channel:
  model: "free_space"
  snr_db: 40.0
  multipath:
    enabled: false
    n_paths: 1

# Clock Configuration
clocks:
  oscillator_type: "TCXO"
  allan_deviation_1s: 1.0e-11
  initial_bias_std: 1.0e-9
  initial_drift_ppm: 1.0
  carrier_freq_hz: 6.5e9
  sco_enabled: false

# Measurement Configuration
measurements:
  type: "ToA"
  range_noise_std: 0.01
  outlier_probability: 0.0
  measurement_rate: 10.0
  use_crlb: true
  min_variance: 1.0e-4

# FAST CONSENSUS CONFIGURATION
consensus:
  algorithm: "consensus_gauss_newton"

  # Optimized for speed
  parameters:
    max_iterations: 100  # Reduced from 500
    consensus_gain: 0.10  # Higher Î¼ for faster convergence
    step_size: 0.4  # More aggressive steps
    gradient_tol: 1.0e-4  # Relaxed tolerance
    step_tol: 1.0e-5  # Relaxed tolerance
    damping_lambda: 1.0e-4

  # Early stopping for speed
  early_stopping:
    enabled: true
    patience: 10  # Stop if no improvement for 10 iterations
    min_delta: 1.0e-3  # 1 mm improvement threshold

  # Adaptive parameters for acceleration
  adaptive:
    enabled: true
    initial_gain: 0.15
    final_gain: 0.05
    schedule: "exponential"  # Decay consensus gain over time

  state_scale: [1.0, 1.0, 1.0, 0.1, 0.1]

# Initialization (same as ideal)
initialization:
  method: "gaussian"
  position_noise_std: 0.5
  clock_bias_std: 1.0e-9
  clock_drift_std: 1.0e-6

# Output Configuration
output:
  save_positions: true
  save_errors: true
  save_convergence_history: true
  format: "json"
  output_dir: "results/fast_30node/"
  metrics:
    - "rmse"
    - "convergence_iterations"
    - "computation_time"

# Simulation Configuration
simulation:
  random_seed: 42
  n_runs: 1
  verbose: true
  log_level: "INFO"

# Performance Targets
benchmarks:
  targets:
    rmse_cm: 1.0  # Target 1 cm
    max_iterations: 50  # Must converge within 50 iterations
    max_time_s: 0.5  # Must complete in 0.5 seconds

  expected:
    rmse_cm: 1.0
    iterations: 49
    time_s: 0.25