# Indoor configuration
# Small room with excellent conditions

seed: 42

area:
  size_m: 10.0

nodes:
  total: 8
  anchors: 4  # Corner anchors

channel:
  bandwidth_hz: 500.0e6  # 500 MHz UWB
  snr_db: 30.0          # Excellent SNR
  min_snr_db: 0.0
  max_range_m: 15.0