# Outdoor configuration
# Large area with challenging conditions

seed: 42

area:
  size_m: 100.0

nodes:
  total: 30
  anchors: 8  # More anchors needed for large area

channel:
  bandwidth_hz: 20.0e6  # 20 MHz WiFi
  snr_db: 15.0         # Moderate SNR
  min_snr_db: -10.0
  max_range_m: 150.0